//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carnet_adresse_contact.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumTel
    {
        public int IdNumTel { get; set; }
        public Nullable<int> IdContact { get; set; }
        public string NumeroTel { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
