//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockProduit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class produit
    {
        public int Idprouit { get; set; }
        public string DenominationProduit { get; set; }
        public string CategorieProuit { get; set; }
        public string QuantiteProduit { get; set; }
        public Nullable<double> PUProduit { get; set; }
    }
}
