//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiColorModernUI.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesure
    {
        public int IdPers { get; set; }
        public Nullable<double> TourP { get; set; }
        public Nullable<double> TourT { get; set; }
        public Nullable<double> TourB { get; set; }
        public Nullable<double> CarrureDev { get; set; }
        public Nullable<double> CarrureDos { get; set; }
        public Nullable<double> LongE { get; set; }
        public Nullable<double> TourBras { get; set; }
        public Nullable<double> HautTG { get; set; }
        public Nullable<double> EcartPS { get; set; }
        public Nullable<double> LongBD { get; set; }
        public Nullable<double> LongPS { get; set; }
        public Nullable<double> LongBusteD { get; set; }
        public Nullable<double> LongBP { get; set; }
        public Nullable<double> HautTD { get; set; }
        public Nullable<double> LongTC { get; set; }
        public Nullable<double> HautEJ { get; set; }
    }
}
